### PR TITLE
Corrects listing behaviour

### PR DESCRIPTION
**Pull request by onyiny-ang**
However, looking further into CLI behaviour, I'm not sure that things are arranged as they should be in the extension.
In the current Tekton Pipelines View:
```
Pipelines 
    > Actual Pipelines
        > PipelineRuns 
            > Taskruns
Tasks
    > Actual Tasks
ClusterTasks
    > Actual ClusterTasks
```
However, this is not how the CLI seems to organize things. Following from the view above, I would have thought `tkn taskruns list pipelinerun-1` would return all of the taskruns in pipelinerun-1 but actually the CLI functionality requires that you call `tkn taskruns list task-1` in order to get the taskruns associated with task-`. . .so now I am thinking the Pipeline View is actually incorrect.
Should TaskRuns fall under the Tasks heading instead of PipelineRuns?

### CODE REVIEW

**Comment by vdemeester** [comment]
> However, this is not how the CLI seems to organize things. Following from the view above, I would have thought `tkn taskruns list pipelinerun-1` would return all of the taskruns in pipelinerun-1 but actually the CLI functionality requires that you call `tkn taskruns list task-1` in order to get the taskruns associated with task-`. . .so now I am thinking the Pipeline View is actually incorrect.
> Should TaskRuns fall under the Tasks heading instead of PipelineRuns?

Yes and no :angel: Conceptually yes, but in real life no or more accurately it depends :joy_cat: (it will make sense I promise :angel:).

So, a `TaskRun` is an execution of a `Task` ; *but* this execution can either be caused by executing a `Task` directly, or by executing a `Pipeline` that will that will create a `PipelineRun` that will induce the creation of `TaskRun`s. 

So in the view, I feel the `Pipeline > PipelineRun > TaskRun` is good as is ; but we could add `Task > TaskRun` where all `TaskRun`s are (aka those executed "alone" and those from a PipelineRun — thus the later would be duplicated)

```
Pipelines 
    > Actual Pipelines
        > PipelineRuns 
            > Taskruns
Tasks
    > Actual Tasks
        > TaskRuns
ClusterTasks
    > Actual ClusterTasks
        > TaskRuns
```

**Comment by gorkem** [comment]
Can't we differentiate between TaskRuns that are associated with a PipelineRun and those are not ? I find it confusing to show duplicate TaskRuns on the UI TBH.

**Comment by vdemeester** [comment]
> Can't we differentiate between TaskRuns that are associated with a PipelineRun and those are not ? I find it confusing to show duplicate TaskRuns on the UI TBH.

We can for sure. I just wonder what a user would expect. I would expect the same as the CLI on the `Task`, aka I see the Task, I can see all the execution of it. We can display a different icon (and have a different context menu if the TaskRun comes from a PipelineRun or not maybe ?)

**Comment by onyiny-ang** [comment]
I made the changes as per @vdemeester 's suggestions. I still have to write the tests so please let me know if it makes sense as is or if there are other recommendations.
cc: @gorkem

**Pull request merged**
