### PR TITLE
Add preview for pipeline tasks

### PR DESCRIPTION
**Pull request by evidolob**
Fix: #150

This PR add `Open Pipeline preview to the Side` command in editor title bar, which open pipeline preview webview.

In webview used [cytoscape](https://js.cytoscape.org/) with [dagre](https://github.com/cytoscape/cytoscape.js-dagre) plugin (to render DAG tree), JS lib to render pipeline task execution diagram

Current demo:
ezgif com-optimize

First diagram on the demo is equal to diagram from [tekton documentation](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#ordering)

Things to do:

- [x] Implement [webview persistence](https://code.visualstudio.com/api/extension-guides/webview#persistence), now all content lost when preview tab switched
- [x] Implement support of vscode theme switching 
- [x] Update diagram on pipeline editing

### CODE REVIEW

**Comment by siamaksade** [comment]
cc @vdemeester @sthaha

**Comment by vdemeester** [comment]
Nice ! :heart_eyes_cat:

**Comment by evidolob** [comment]
Update diagram preview on pipeline change in editor demo:
ezgif com-video-to-gif (3)
cc @siamaksade

**Comment by evidolob** [comment]
Theme switching demo:

ezgif com-video-to-gif (4)

**Comment by evidolob** [comment]
Theme switching demo:

ezgif com-video-to-gif (4)

**Pull request merged**
