### PR TITLE
Add TaskRuns in the tree as a root node

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #198 
Screen Recording 2020-04-07 at 7 28 57 PM

### CODE REVIEW

**Comment by siamaksade** [comment]
Should it be plural `TaskRuns`?

**Comment by sudhirverma** [comment]
@siamaksade 
Screenshot 2020-04-07 at 8 16 17 PM

**Comment by siamaksade** [comment]
Reorder is valid here too. TaskRuns after ClusterTasks

**Comment by sudhirverma** [comment]
@siamaksade @gorkem 
Screenshot 2020-04-08 at 7 03 41 PM

**Pull request merged**
