### PR TITLE
show reason when pipelinerun pass or fail

### LINKED ISSUE #193: Failing PipelineRun with CouldnGetTask error are not shown
If i start a pipeline which contains a not existing task i don't have any message on vscode and even if i list pipelineruns i cannot see them.

image

image

As you can see all pipeline failing with the "CouldnGetTask" message error are not displayed.

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #193 

Screenshot 2020-05-24 at 9 09 46 PM

### CODE REVIEW

**Comment by evidolob** [comment]
@siamaksade Can you verify this?

**Comment by siamaksade** [comment]
@evidolob could we show the failure reason on the tooltip? The tree window is often small and the text won't fit there.

**Comment by evidolob** [comment]
I like the idea of showing failure reason in tooltip,
@sudhirverma WDYT?

**Comment by sudhirverma** [comment]
My first thought was to keep in tooltip

> I like the idea of showing failure reason in tooltip,
> @sudhirverma WDYT?

Yaa that's a good idea I will remove from the description and show the reason in tooltip :)

**Comment by sudhirverma** [comment]
@siamaksade  @evidolob New Screenshot.
Screenshot 2020-05-25 at 5 50 55 PM

**Review by siamaksade — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Pull request merged**
