### PR TITLE
Start task and ClusterTask from wizard.

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #489

### CODE REVIEW

**Comment by evidolob** [comment]
@sudhirverma Start ClusterTask doesn't work for me. I got
```
fail to fetch pipeline: undefinedError from server (NotFound): pipelines.tekton.dev "tkn" not found
``` 
Notification after I press `start` button on wizard page.

Also I see this trace:
```
rejected promise not handled within 1 second: TypeError: Cannot read property 'metadata' of undefined
/Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js:5
stack trace: TypeError: Cannot read property 'metadata' of undefined
	at Object.<anonymous> (/Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/addtrigger.js:81:55)
	at Generator.next (<anonymous>)
	at /Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/addtrigger.js:12:71
	at new Promise (<anonymous>)
	at /Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/addtrigger.js:8:12
	at Object.k8sCreate (/Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/addtrigger.js:74:12)
	at Object.<anonymous> (/Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/start-pipeline-from-json.js:27:28)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/yevhen/work/redhat/vscode-tekton/out/src/tekton/start-pipeline-from-json.js:9:58)
```

**Comment by sudhirverma** [comment]
> @sudhirverma Start ClusterTask doesn't work for me(I try to start `tkn` ClusterTask). I got:
> 
> ```
> fail to fetch pipeline: undefinedError from server (NotFound): pipelines.tekton.dev "tkn" not found
> ```
> 
> Notification after I press `start` button on wizard page.

I have tried to start `tkn` ClusterTask and it was working for me.

**Comment by evidolob** [comment]
I'v restart CRC and ClusterTask now start form wizard, but it always fails.
When I get log for such TaskRun I get:

```
task tkn has failed: invalid input params for task tkn: param types don't match the user-specified type: [ARGS]
Error: pod for taskrun tkn-gmv8b not available yet
```

**Comment by sudhirverma** [comment]
@evidolob now it should work

**Review by evidolob — APPROVED** [review]

**Pull request merged**
