### PR TITLE
Enable add trigger command if trigger is installed

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #419

### CODE REVIEW

**Review by lstocchi — CHANGES_REQUESTED** [review]
Still not working for me. I did a quick debug and the issue is that it tries to verify my tekton trigger version before the tkn cli is actually found. 
If i put a breakpoint inside the `version` method (in tknversion.ts) the value of result i get is: 
image

I see that in the `activate` method there are the two calls

```
detectTknCli();
triggerDetection();
```

an idea could be to change it to
`detectTknCli().then(() => triggerDetection());`
so the triggerDetection will run after the tkn cli is actually detected.

**Comment by sudhirverma** [comment]
Thanks, @lstocchi :) can you review again.

**Review by lstocchi — APPROVED** [review]
It works fine for me now :)

**Review by evidolob — APPROVED** [review]
LGTM

**Pull request merged**
