### PR TITLE
feat: update tekton scheme to v0.56

### PR DESCRIPTION
**Pull request by l-qing**
Ref: https://github.com/redhat-developer/intellij-tekton/pull/660

### CODE REVIEW

**Comment by zsirotto** [comment]
Any plans to merge this?

**Comment by kamok** [comment]
Fairly interested in this too. @vdemeester sorry for the ping. We're a team at IBM who heavily uses Tekton and want to better our developer + innersource environment with tekton linting.

**Review by khrm — COMMENTED** [review]
/lgtm 
/approve

**Comment by khrm** [comment]
We need to add stepaction CRD also.

**Review by khrm — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
