### PR TITLE
Add PipelineRun in the tree as a root node

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #197 
Screen Recording 2020 04 07 at 2 00 44 PM

### CODE REVIEW

**Comment by siamaksade** [comment]
Should it be plural like the other nodes?  `PipelineRuns` in other words

**Comment by sudhirverma** [comment]
@siamaksade 
Screenshot 2020-04-07 at 8 25 03 PM

**Comment by gorkem** [comment]
Should we re-order the root level container nodes. For instance put `PipelineRuns` after `Pipelines`

**Comment by sudhirverma** [comment]
@gorkem 
Screenshot 2020-04-08 at 12 16 54 PM

**Comment by gorkem** [comment]
looks better @sudhirverma you probably need to do the same for `TaskRuns` if you have not done already.

**Pull request merged**
