### PR TITLE
wizard to restart pipelinerun.

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #351

### CODE REVIEW

**Review by evidolob — APPROVED** [review]
LGTM
I'm not sure why you delete 'Start Las Run' command?

**Comment by sudhirverma** [comment]
> LGTM
> I'm not sure why you delete 'Start Las Run' command?

I have removed the `Start Last Run` command because we `restart` command for each pipelineRun.

**Comment by evidolob** [comment]
As for me they do similar stuff but they have differed purpose. Is @siamaksade asked to delete it?

**Comment by sudhirverma** [comment]
> As for me they do similar stuff but they have differed purpose. Is @siamaksade asked to delete it?

nope. @siamaksade Do you want me to keep `Start Last Run` and `Resart` both command or only `Restart` should work?

**Pull request merged**
