### PR TITLE
(feat) add tekton snippets

### LINKED ISSUE #24: Support for snippets
add support for snippets that allows to create tekton resource yamls quickly.

### PR DESCRIPTION
**Pull request by kameshsampath**
- add tekton snippets for quick ceation of Tektoncd YAMLS

fixes: #24

### CODE REVIEW

**Comment by kameshsampath** [comment]
@vdemeester  - please hold merging this, got some fixes and addition will push back

**Comment by vdemeester** [comment]
@kameshsampath ok :angel:

**Comment by kameshsampath** [comment]
@vdemeester  - its now good for review and merge

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Pull request merged**
