### PR TITLE
Show condition run as child for taskrun

### LINKED ISSUE #277: Use condition name for 'Condition' node in pipeline run child nodes
Now if task has condition we add item in the tree with task name not with condition name:
Screenshot 2020-05-07 at 17 43 38

We need to use condition name for that tree item.

### PR DESCRIPTION
**Pull request by evidolob**
As side effect of this PR, tree load for PipelineRun and it child become more faster,
now we use only PipelineRun data to build subtree for pipelinerun, 
previously we fetch TaskRun's for each PipelineRun

Example:
Screenshot 2020-05-20 at 12 09 55

Fix: #277

### CODE REVIEW

**Review by sudhirverma — COMMENTED** [review]
I am getting an error while starting a condition pipeline 

Screenshot 2020-05-20 at 5 35 45 PM

**Comment by evidolob** [comment]
Current state demo:
ezgif com-video-to-gif (12)

@siamaksade I had to introduce new state icon for task in pipelinerun, which indicates that task is pending, WDYT?

**Comment by siamaksade** [comment]
@evidolob the pending icon looks good, and better representative of that state of pipelinerun. Could we also use a different icon for the condition? 

About "Open in Editor", showing and error is fine. The error message should explain that the taskrun is not started yet and user can open it in the editor as soon as it starts running.

**Comment by evidolob** [comment]
@siamaksade Yes we can, I'm not sure which one to use. As in general condition is also taskrun, and may have same states as regular taskrun.

**Comment by evidolob** [comment]
I think we can use our icons for other resources(with abbreviation ) and change colors of it depending on state(success/fail/pending/canceled)
WDYT?

**Comment by evidolob** [comment]
Latest state demo:
ezgif com-video-to-gif (13)

**Review by sudhirverma — APPROVED** [review]

**Pull request merged**
