### PR TITLE
Do not block extension activation with 'tkn' detection

### PR DESCRIPTION
**Pull request by evidolob**
Fix: #296

### CODE REVIEW

**Comment by evidolob** [comment]
@sudhirverma Can you elaborate more how you get:
> while starting pipeline I got an error Failed to start Pipeline with error 'undefined/bin/sh: tkn: command not found '. 
?

**Comment by sudhirverma** [comment]
I remove the `tkn` from my local system and I skip the download option when it appears.

while starting the pipeline I got the error that `tkn command not found`.

**Comment by sudhirverma** [comment]
I think we should not disable `tkn` command. We should ask for download when we trigger a command which required `tkn` Cli if `tkn` is not detected.

**Comment by evidolob** [comment]
I not agree, behaviour will be the same as

> I remove the `tkn` from my local system and I skip the download option when it appears.
> 
> while starting the pipeline I got the error that `tkn command not found`.

So why we allow to execute something that lead to error, when we exactly know that?
We block all commands that we know that will not work, and when we detect that `tkn` installed we unblock them.

**Comment by sudhirverma** [comment]
we will not ask to download `tkn` at the beginning we will ask to download when we use `tkn` command. for e.g: in start command, we required `tkn` Cli we will show the download option at that time if the user `cancels or skip` then we will not execute the `start command` and show a warning message and in next start, we will again show the `download option` if it is not detected.

**Comment by evidolob** [comment]
But we has agreement that we will ask for tkn at the beginning.
It may be confusing why we show tree and has half of extension working and then we suddenly start asking for some cli tool.

**Comment by siamaksade** [comment]
We should always ask to download the `tkn` command in the beginning if not detected.

If user skips and then clicks on "start pipeline" and sees the download `tkn` notification, would she understand why it is displayed? Would users be able to connect the dots that I see it because "start pipeline" needs the `tkn` command and if they don't install it it wouldn't execute? I'm worried they won't understand this and would just wonder why the pipeline is not getting started.

**Comment by evidolob** [comment]
@siamaksade I this PR we ask user to install `tkn` on extension start, if it not installed I disable all commands which uses `tkn` like start, stop, view logs.
Now we show:
`Cannot find Tekton CLI 0.9.0 for interacting with Tekton Pipelines.`
We may change that message to:
`Cannot find Tekton CLI 0.9.0 for interacting with Tekton Pipelines. Commands which requires Tekton CLI will be disabled.`

**Comment by siamaksade** [comment]
@evidolob makes sense. The update message is more clear so user knows why those commands don't work and what they should do to enable them.

**Pull request merged**
