### PR TITLE
Display project/namespace

### PR DESCRIPTION
**Pull request by sudhirverma**
Fix: #287 

Screenshot 2020-06-04 at 1 27 06 PM

### CODE REVIEW

**Comment by sudhirverma** [comment]
@siamaksade & @evidolob we need a new icon for namespace similar to other icons `NS`(NameSpace).

**Comment by evidolob** [comment]
I think we need icon for project/namespace.
And maybe add more description for project/namespace node:
Screenshot 2020-06-04 at 09 36 22

In this case `default` can be `Project: default` or `Namespace: default` in case k8s cluster.

@siamaksade WDYT?

**Comment by evidolob** [comment]
@sudhirverma This PR has merge conflicts, can you resolve them?

**Comment by gorkem** [comment]
This looks a bit weird to me visually. Also logically we have `ClusterTasks` on that view that are not really on the scope of the namespace

**Comment by siamaksade** [comment]
Should we just say `Active Namespace: default` without icon in order to separate it from the Tekton resources? Could the background be in a different color to make it look like a title bar?

**Comment by sudhirverma** [comment]
@siamaksade and @evidolob we can also keep the namespace icon same as dev console UI Namespace badge color.

Screenshot 2020-06-09 at 10 58 12 PM

**Comment by evidolob** [comment]
@siamaksade @sudhirverma 
I have an idea, that maybe instead of having this, we can create issue/contribute PR to k8s extension to show current namespace in toolbar, similar to current git branch. 
Other our extensions may have similar problem and desire to show namespace, and we can solve it in one place.

cc @gorkem @lstocchi

**Comment by gorkem** [comment]
> I have an idea, that maybe instead of having this, we can create issue/contribute PR to k8s extension to show current namespace in toolbar, similar to current git branch.

This is exactly how I [described](https://github.com/Azure/vscode-kubernetes-tools/issues/757#issuecomment-632373422) it on kubernetes extension.  @lstocchi has an [ongoing PR ](https://github.com/Azure/vscode-kubernetes-tools/pull/767) for this. I think it does not address the toolbar (yet?).

The root cause of this bad UX needs to be fixed on k8s extension especially since the last version of the vscode allows to move views.

**Comment by lstocchi** [comment]
Sorry but i think i am missing something about the toolbar. By toolbar you mean the one below?
image

If so, i don't get how you can work on the k8s tools to show the namespace on the tekton side. Even if you move the tekton view inside the k8s one, you will have something like 
image

At this point what's your plan? To show the namespace instead of the `KUBERNETES` title?

**Comment by evidolob** [comment]
@lstocchi Yes, I mean status bar, sorry.

In case if we add current namespace in to status bar, it will be visible across all extensions, so there are no need to do something in other k8s extensions. And there are no need to switch views to see current namespace. 

In case Tekton, now we can add namespace in tree view title:
Screenshot 2020-06-23 at 09 51 13
Instead of having separate tree item for namespace

**Comment by lstocchi** [comment]
Ok, i got what is your idea now. 
Well, if you plan to keep all nodes on the same level it can also work to add the namespace in the header. 

I just wanted to be sure you know that the status bar can be hidden and that, afaik, Microsoft is changing PM related to k8s-tools project so I think the time to see our PR approved will be longer as we need to wait their feedback :/
But if you also show the namespace somewhere else you should be fine.

**Comment by siamaksade** [comment]
I agree that it's much better experience to see the active namespace in the status bar

**Comment by sudhirverma** [comment]
closing this as implemented in k8s extension.

**Pull request closed without merging**
