### PR TITLE
Allow install Pipeline from TektonHub

### LINKED ISSUE #610: Add support to install pipelines from Hub
It looks like the Hub also contains pipelines now. We should add support for them as well.
I made a test with `build-push-gke-deploy` pipeline
Current behavior 
image

When trying to install it 
image

### PR DESCRIPTION
**Pull request by evidolob**
Resolve: #610

Demo:

https://user-images.githubusercontent.com/929743/141270570-291866dc-0f52-4f08-b06c-287ada3a0c0d.mov

### CODE REVIEW

**Comment by sudhirverma** [comment]
I am getting an option to install pipeline as clustertask
Screenshot 2021-11-12 at 2 15 20 PM

**Comment by evidolob** [comment]
@sudhirverma  That should be removed now.

**Comment by sudhirverma** [comment]
clicking on uninstall button always stays on Uninstalling stay and if you install the pipeline from editor view it does not change the state from install to uninstall.

**Comment by evidolob** [comment]
That expected, as if you install pipeline manually, the yaml doesn't contain label which indicate that pipeline from TektonHub

**Comment by sudhirverma** [comment]
> That expected, as if you install pipeline manually, the yaml doesn't contain label which indicate that pipeline from TektonHub

I have not installed it manually. I install it from tektonHub.

**Comment by evidolob** [comment]
OK, that should be fixed now

**Review by sudhirverma — APPROVED** [review]

**Pull request merged**
