### PR TITLE
Fix upgrade/downgrade tasks from hub

### PR DESCRIPTION
**Pull request by evidolob**
Fix: #499

### CODE REVIEW

**Review by sudhirverma — COMMENTED** [review]
I was getting the error when it takes time to update the status of the install.

Screenshot 2021-02-09 at 4 49 50 PM

**Comment by evidolob** [comment]
@sudhirverma It should be fixed now

**Comment by sudhirverma** [comment]
I have seen this error when I launch the extension

Screenshot 2021-02-10 at 1 19 50 PM

**Comment by sudhirverma** [comment]
everything looks good but when I click multiple times on the install button I get the error.

Screenshot 2021-02-10 at 4 23 31 PM

**Comment by evidolob** [comment]
@sudhirverma I fix buttons, it should work now

**Comment by sudhirverma** [comment]
> @sudhirverma I fix buttons, it should work now

It is still not fixed tektonhub UI in editor and tektonhub in tree view takes time to update the button from install -> installing.

**Comment by evidolob** [comment]
It is change fast on my laptop:

https://user-images.githubusercontent.com/929743/107624638-d9688580-6c63-11eb-914c-bff457a760f2.mov

**Comment by sudhirverma** [comment]
> > @sudhirverma I fix buttons, it should work now
> 
> It is still not fixed tektonhub UI in editor and tektonhub in tree view takes time to update the button from install -> installing
> and when I install from tektonhub tree view it doesn't update the UI.
> 
> Screenshot 2021-02-11 at 3 51 43 PM

I will create a separate issue this one

**Review by sudhirverma — APPROVED** [review]

**Pull request merged**
